i forgor packages and some configs

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -1,5 +1,4 @@
 #!/bin/bash
-# https://github.com/JaKooLit
 
 # Check if running as root. If root, script will exit
 if [[ $EUID -eq 0 ]]; then
@@ -275,7 +274,7 @@ for PKG1 in foot swaybg swaylock-effects wofi wlogout mako grim slurp wl-clipboa
     fi
 done
 
-for PKG2 in rofi-lbonn-wayland librewolf zsh zsh-you-should-use zsh-autosuggestions starship exa tere bat qt5ct btop jq gvfs gvfs-mtp ffmpegthumbs mpv python-requests pamixer brightnessctl xdg-user-dirs viewnior mpv network-manager-applet cava; do
+for PKG2 in rofi-lbonn-wayland librewolf zsh zsh-you-should-use zsh-autosuggestions starship exa tere bat qt5ct btop jq gvfs gvfs-mtp ffmpegthumbs mpv python-requests pamixer brightnessctl xdg-user-dirs viewnior mpv network-manager-applet cava wireplumber; do
     install_package  "$PKG2" 2>&1 | tee -a "$LOG"
     if [ $? -ne 0 ]; then
         echo -e "\e[1A\e[K${ERROR} - $PKG2 install had failed, please check the install.log"
@@ -522,9 +521,12 @@ if [[ $CFG =~ ^[Yy]$ ]]; then
     cp -r config/mpv ~/.config/ || { echo "Error: Failed to copy mpv config files."; exit 1; } 2>&1 | tee -a "$LOG"
     cp -r config/mpd ~/.config/ || { echo "Error: Failed to copy mpd config files."; exit 1; } 2>&1 | tee -a "$LOG"
     cp -r config/pulse ~/.config/ || { echo "Error: Failed to copy pulse config files."; exit 1; } 2>&1 | tee -a "$LOG"
+    cp -r config/swaylock ~/.config/ || { echo "Error: Failed to copy swaylock config files."; exit 1; } 2>&1 | tee -a "$LOG"
     cp -r config/zsh/.zshrc ~/ || { echo "Error: Failed to copy .zshrc config files."; exit 1; } 2>&1 | tee -a "$LOG"
     cp -r config/starship.toml ~/.config/ || { echo "Error: Failed to copy starship config files."; exit 1; } 2>&1 | tee -a "$LOG"
     cp -r config/.bashrc ~/ || { echo "Error: Failed to copy bash config files."; exit 1; } 2>&1 | tee -a "$LOG"
+    cp -r config/.zprofile ~/ || { echo "Error: Failed to copy zprofile!."; exit 1; } 2>&1 | tee -a "$LOG"
+    cp -r config/.gtkrc-2.0 ~/ || { echo "Error: Failed to copy gtk2.0 rc!."; exit 1; } 2>&1 | tee -a "$LOG"
     cp -r config/gtk-3.0 ~/.config/ || { echo "Error: Failed to copy gtk config files."; exit 1; } 2>&1 | tee -a "$LOG"
     mkdir -p ~/.local/
     mkdir -p ~/.local/bin
